services:
    php:
        container_name: php-node-test_php-server
        image: php-node-test/php-server
        env_file:
            - .env
        build:
            context: ./php
            dockerfile: ./php.Dockerfile
            args:
                PHP_WORKING_DIR: ${PHP_WORKING_DIR}
                PHP_HOST: ${PHP_HOST}
                PHP_PORT: ${PHP_PORT}
        volumes:
            - ./php/:${PHP_WORKING_DIR}
        ports: 
            - "8000:${PHP_PORT}"
        # tty: true
        # stdin_open: true
    
    node:
        container_name: php-node-test_node-server
        image: node
        user: "node"
        env_file:
            - .env
        build:
            context: ./node
            dockerfile: ./node.Dockerfile
            args:
                NODE_WORKING_DIR: ${NODE_WORKING_DIR}
        volumes:
            - ./node/:${NODE_WORKING_DIR}
        # tty: true
        # stdin_open: true