services:
    # php:
    #     image: php-node-networks-test/php-server
    #     env_file:
    #         - .env
    #     build:
    #         context: ./php
    #         dockerfile: ./php.Dockerfile
    #         args:
    #             PHP_WORKING_DIR: ${PHP_WORKING_DIR}
    #             PHP_HOST: ${PHP_HOST}
    #             PHP_PORT: ${PHP_PORT}
    #     volumes:
    #         - ./php/:${PHP_WORKING_DIR}
    #     networks:
    #         my_custom:
    #             ipv4_address: ${PHP_IP4}
    
  db:
    image: mysql
    command: --authentication_policy=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./data/:/var/lib/mysql
      - ./init_mysql/:/docker-entrypoint-initdb.d


    
# networks:
#     custom:
#         driver: bridge
#         ipam:
#             config:
#                 - subnet: 192.168.1.0/8
#                   gateway: 192.168.1.1