services:
    php:
        container_name: php-test
        image: phpforredis
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./php.Dockerfile
            args:
                PHP_WORKING_DIR: ${PHP_WORKING_DIR}
        volumes:
            - ./:${PHP_WORKING_DIR}
        # tty: true
        # stdin_open: true

    redis:
        container_name: redis-test
        image: redis
        command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASS} --port ${REDIS_PORT}
        ports:
            - "6379:${REDIS_PORT}"